### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Sherex** [Sherex/ansible-arch#1]
# Configuration
- dhclient
  - [ ] Start the service after the interface is up
- qutebrowser
  - [ ] Sync bookmarks (syncthing?)
- ssh
  - [ ] Create ssh keys (ed25519 and rsa)
  - [ ] Generate `~/.ssh/config` from inventory
  - [ ] Add the new public key to the hosts it should be able to connect to
- user
  - [ ] Create a config dir for bash where other roles can place shell configurations

# Packages to add
## High
- [ ] snapper
- [ ] bitwarden-cli
- [ ] neovim (Lunarvim)
- [ ] xwayland
- [ ] borg + borgmatic
- [x] [fnm](https://github.com/Schniz/fnm)
- [ ] teams-for-linux

## Low
- [ ] dbeaver

## Nice to have
- Auth
  - [ ] [Fprint](https://wiki.archlinux.org/title/Fprint) (PAM fingerprint authentication)
  - [ ] [Howdy](https://wiki.archlinux.org/title/Howdy) (PAM face authentication)
- [ ] [xxh](https://github.com/xxh/xxh)
- [ ] nmap
- rofi plugins [more plugins](https://github.com/davatorium/rofi/wiki/User-scripts):
  - [x] community/rofi-calc
  - [ ] aur/rofi-greenclip
  - [ ] aur/rofi-surfraw-git
  - [ ] aur/rofi-search-git
  - [ ] aur/rofi-bluetooth-git
  - [x] aur/bitwarden-rofi-git
  - [ ] aur/rofi-rbw
  - [ ] aur/rofi-1pass
  - [ ] aur/rofi-power-menu
  - [ ] aur/rofi-blezz
  - [ ] aur/buku-rofi-git
